[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  # Disabling Edge to ensure Prisma compatibility
  # NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
